{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh", "swish"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.1, "conditions": [], "values": [0.1, 0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 2, "max_value": 512, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 1, "max_value": 30, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "l1_weight", "default": 0.1, "conditions": [], "values": [0.1, 0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "dropout", "default": 0.1, "conditions": [], "values": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6], "ordered": true}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 1, "max_value": 30, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 1, "max_value": 30, "step": 1, "sampling": "linear"}}], "values": {"activation": "tanh", "learning_rate": 0.01, "units": 226, "num_layers": 3, "units_0": 12, "l1_weight": 0.001, "dropout": 0.5, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 4, "tuner/round": 0, "units_1": 1, "units_2": 1}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\eeels\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\eeels\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 260, in _run_and_update_trial\n    self.oracle.update_trial(\n  File \"c:\\Users\\eeels\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\oracle.py\", line 108, in wrapped_func\n    ret_val = func(*args, **kwargs)\n  File \"c:\\Users\\eeels\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\oracle.py\", line 512, in update_trial\n    self._check_objective_found(metrics)\n  File \"c:\\Users\\eeels\\anaconda3\\lib\\site-packages\\keras_tuner\\src\\engine\\oracle.py\", line 780, in _check_objective_found\n    raise ValueError(\nValueError: Objective value missing in metrics reported to the Oracle, expected: ['accuracy'], found: dict_keys(['loss', 'mae', 'val_loss', 'val_mae', 'multi_objective'])\n"}